---
- name: Install Apache
  hosts: all
  become: yes

  vars:
     source_file: ./index.html
     destin_file: /var/www/html

  tasks:
# 1. В этой части будет переменная которая определяет версию Linux в (п.3 и 4)
  - name: Check version Linux
    debug: var=ansible_os_family

# 2. Для установки на Debian и CentOS используем when: условия для (п.3 и 4)

# 3. Устанавливаем Apache на Debian где Apache=apache2 через apt
  - name: Install Apache web Server Debian
    apt: name=apache2 update_cache=yes state=latest
    when: ansible_os_family== "Debian"

# 4. Устанавливаем Apache на CentOS где Apache=httpd через yum
  - name: Install Apache web Server CentOS
    yum: name=httpd update_cache=yes state=latest
    when: ansible_os_family== "CentOS"

# 5. Блок отвечающий за копирование файлов в папку www на удаленном сервере из vars
  - name: Copy files in www CentOS
    copy: src={{ source_file }} dest={{ destin_file }}
    notify: Restart Apache CentOS

  - name: Copy files in www Debian
    copy: src={{ source_file }} dest={{ destin_file }}
    notify: Restart Apache Debian

# 6. Этот блок отвечает за запуск сервиса, для него так же используем when: условия
  - name: Start CentOS
    service: name=httpd state=started enabled=yes
    when: ansible_os_family== "CentOS"

  - name: Start Debian
    service: name=apache2 state=started enabled=yes
    when: ansible_os_family== "Debian"

# 7. Добавим handlers для указания якоря "Restart Apache CentOS/Debian", для п.5
  handlers:
  - name: Restart Apache CentOS
    service: name=httpd state=restarted

  - name: Restart Apache Debian
    service: name=apache2 state=restarted
